apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pfeg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-pfeg@sha256:9cb5d8af58f5867b272496dbf7f9117784c5e781eaf0ee0734e31a0bce0a2d0e
        name: my-nodejs
        resources: {}
status: {}
